// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "vue" {
  export interface GlobalComponents {
    "Fa6Solid:0": typeof import("~icons/fa6-solid/0")["default"];
    "Fa6Solid:xmark": typeof import("~icons/fa6-solid/xmark")["default"];
    "IFa6Solid:0": typeof import("~icons/fa6-solid/0")["default"];
  }
}

export {};
